### ISSUE TITLE
Section Revisions: setup/deploy-linuxjumpbox.md

### ISSUE THREAD

**Issue by rajeshagadi** [Microsoft/MTC_ContainerCamp#12]
On Step 6. Finally, on the 'Summary' page, review the settings, then click 'OK',   Revise "OK" to "Purchase" and revise 'Summary' page to 'Purchase' page

Under Connect to the Jumpbox section, expand the steps on how with following (Not everyone may be aware of how SSH works:
Run your SSH, copy Public IP address from the Azure VM overview blade. Copy in to SSH, ok, Yes on the Security Alert etc.   

Under Install the Azure cli: Provide context that, run below command from the SSH bash command.

**Comment by amazaheri** [comment]
@rajeshagadi  Can you apply the update along with other changes and do a PR?

**Comment by rajeshagadi** [comment]
Updated
