### ISSUE TITLE
Section Revisions: MTC_ContainerCamp/labtwo/buildimage.md

### ISSUE THREAD

**Issue by rajeshagadi** [Microsoft/MTC_ContainerCamp#14]
Section : Review Dockerfile>Revise the path in instruction "cd ~/ContainerCamp/labtwo" to "cd ~/**MTC_**ContainerCamp/labtwo

**Comment by amazaheri** [comment]
@rajeshagadi  Can you apply the update along with other changes and do a PR?

**Comment by rajeshagadi** [comment]
Updated
