### ISSUE TITLE
Section Revision: https://github.com/Microsoft/MTC_ContainerCamp/blob/master/labtwo/oms/oms4containers.md

### ISSUE THREAD

**Issue by rajeshagadi** [Microsoft/MTC_ContainerCamp#16]
Under Task 1: Prepare OMS>2. Retrieve the workspace id and primary key>Step iii>Revise "Click on Data Sources connected tile" to "Click on Settings Gear from the top right OMS bar."

Under Step iv : Make note of (copy somewhere) the Workspace ID and Primary Key. Run the following:>Revise to give clarity "run from your linux jumpbox"

Task 2: Steps will error out including the sudo command. Hence there are no linux servers listed in Task 3.

At then end of this lab, we are instructing to remove the docker image, but it is not clear why to remove only the image.

**Comment by amazaheri** [comment]
@rajeshagadi Please apply the changes under Modules/oms and include as part of your PR.

**Comment by rajeshagadi** [comment]
Validated and revised the page.
