### ISSUE TITLE
Missing pages in WIP Branch

### ISSUE THREAD

**Issue by rajeshagadi** [Microsoft/MTC_ContainerCamp#17]
Files Labs 2 through 5 are missing in WIP.  Please fix the issue in order for the QA team to proceed. Hence all the links form the main/root page are not working.

**Comment by amazaheri** [comment]
Hi Rajesh, since we change the structure and modules names feel free to update the main readme to point to each modules and submit a PR :) All files should be copied from old structure to new folders

**Comment by amazaheri** [comment]
Closing this as Rhett is working on updates.
