### ISSUE TITLE
Swarm Module:  'docker info' doesn't work. (wip branch)

### ISSUE THREAD

**Issue by larryms** [Microsoft/MTC_ContainerCamp#19]
From Rajesh:
Lab 4: Connect to the Cluster >Docker Info>Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
 
Tried following (https://forums.docker.com/t/cannot-connect-to-the-docker-daemon-is-the-docker-daemon-running-on-this-host/8925/3): No luck
 
 sudo service docker stop
sudo nohup docker daemon -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock &

**Comment by larryms** [comment]
From Rajesh:  
I have tried two different approach: 
 
Fix by sudo vi /etc/default/docker
add following option to the file

DOCKER_OPTS="-s overlay"

then

systemctl restart docker.service

 
Did not solve.
 
Second option, simply recreate the swarm cluster. Same above issue.

**Comment by rajeshagadi** [comment]
This issue was related to older module based on the Docker Swarm. Not relevant now.  Larry then wrote the new lab based on Swarm Mode in the WIP. In the WIP module all works.
