### ISSUE TITLE
Java web container - CrashLoopBackOff

### ISSUE THREAD

**Issue by richross** [Microsoft/MTC_ContainerCamp#20]
Deployed the ReadlingList app as part of Kubernetes lab.  Web container shows status of CrashLoopBackOff.  Repeated steps and reproduced the error.

PS C:\devcontainers\bentley\modules\kubernetes\src\deploy> kubectl get svc web
NAME      TYPE           CLUSTER-IP     EXTERNAL-IP    PORT(S)        AGE
web       LoadBalancer   10.0.179.251   52.183.76.51   80:31610/TCP   3h
PS C:\devcontainers\bentley\modules\kubernetes\src\deploy> kubectl get pods
NAME                    READY     STATUS             RESTARTS   AGE
mysql-617383297-dcs6x   1/1       Running            0          3h
web-3734429008-ztpkn    1/2       CrashLoopBackOff   6          9m

**Comment by amazaheri** [comment]
Assigned to @JeffBrand

**Comment by richross** [comment]
I have this working now and updated the documentation for the additional step.  This may be a separate issue, but does the mysql db have data in it?  The webpage loads but it has no data for the New Books for You.

**Comment by RaviTella** [comment]
Hi @richross  I am the culprit. I will have it fixed within the next hour. The URLs for the images are served by the recommendation service. The URLs point to a storage account in Houston MTC Subscription which I accidentally deleted as a part of my monthly cleanup process.  For now, I will recreate it in the Houston subscription. In the next sprint I will move them to EXP sub and update the code and push new image for the recommendation service.If your .net core is using the same images then you will have to update it too.

**Comment by RaviTella** [comment]
@richross I have recreated the storage account with the images. Its working now.

**Comment by amazaheri** [comment]
@richross  let me know if its working so we can close this as resolved.

**Comment by richross** [comment]
Just confirmed after reviewing Ravi's comment above.  Thanks Ravi!  Will close this one out.
