### ISSUE TITLE
MTC_ContainerCamp/modules/swarm/part1/deploy-docker-swarm.md

### ISSUE THREAD

**Issue by rajeshagadi** [Microsoft/MTC_ContainerCamp#24]
The last step to integrate the OMS, error with following:

azureuser@swarmm-master-50727103-0:~$ docker service create --name omsagent --mode global --mount type=bind, \
>  source=/var/run/docker.sock,destination=/var/run/docker.sock --secret source=WSID, \
>  target=WSID --secret source=KEY,target=KEY -p 25225:25225 -p 25224:25224/udp \
>  --restart-condition=on-failure microsoft/oms:test1
invalid argument "type=bind," for --mount: invalid field '' must be a key=value pair
See 'docker service create --help'.

![image](https://user-images.githubusercontent.com/17166696/31900520-81111354-b7d3-11e7-83e6-cd0ec1779f2d.png)

**Comment by larryms** [comment]
fixed; created pull request

**Comment by rajeshagadi** [comment]
Hi Larry,

Your updated script to pick up the AGENTFQDN is getting the agent name fqdn:

![image](https://user-images.githubusercontent.com/17166696/32197829-fe6a8538-bd82-11e7-9d15-08650ae1c227.png)

**Comment by larryms** [comment]
I think I see the issue: The jmespath script that sets AGENTFQDN  was written assuming the user has only one ACS cluster.  In your example, you have two clusters:  acskubernetes & mySwarmCluster.   In this case, you could pull the correct MASTERFQDN & AGENTFQDN by running:
```
MASTERFQDN=$(az acs list -o tsv --query [1].masterProfile.fqdn); echo $MASTERFQDN
AGENTFQDN=$(az acs list -o tsv --query [1].agentPoolProfiles[0].fqdn); echo $AGENTFQDN
```
Notice in this case I changed the [0] to [1] to force the jmespath to use the 2nd json object.  This is not generalized of course; we'd need to create an updated query to generalize this.

**Comment by larryms** [comment]
fixed per commit today.
