### ISSUE TITLE
ACI Module: Task 2

### ISSUE THREAD

**Issue by rajeshagadi** [Microsoft/MTC_ContainerCamp#37]
In Task 2: after the .cproj has been updated, the command "dotnet restore" fails:

![image](https://user-images.githubusercontent.com/17166696/32196588-7547a1a4-bd7e-11e7-8eab-3a6da84bb565.png)

Caveat: Coming from Task 1. The TargetFramework was netcoreapp2.0. So I corrected to 1.1 and this error seems to continue to occur.

**Comment by richross** [comment]
Closing this issue out as changes included in PR #38.
