### ISSUE TITLE
Consolidate Azure CLI install

### ISSUE THREAD

**Issue by rajeshagadi** [Microsoft/MTC_ContainerCamp#41]
As I reviewed each modules, there are references to getting the Azure CLI many ways. The new AKS module lists all flavors. For vNext we should move the all flavors from AKS module to the consolidated Setup module on all the options and then from each module simply refer back.

**Comment by amazaheri** [comment]
Agreed perhaps under Setup module

**Comment by amazaheri** [comment]
Hi @rajeshagadi where are you with this item?
