### ISSUE TITLE
"az aks create" limited to ukwest,westus2 regions?

### ISSUE THREAD

**Issue by msftkru** [Microsoft/MTC_ContainerCamp#42]
Looks like AKS is limited to a couple regions

![image](https://user-images.githubusercontent.com/22481237/32247355-716493e6-be58-11e7-9511-e46c9d312ab3.png)

https://github.com/microsoft/MTC_ContainerCamp/blob/WIP/modules/kubernetes/kubernetes-with-ACR.md

**Comment by amazaheri** [comment]
correct while in Preview. I believe @richross  added that to guide already.

**Comment by msftkru** [comment]
reading is fundamental ;) it is noted in the doc already.

**Comment by amazaheri** [comment]
This may be helpful as well : https://blogs.msdn.microsoft.com/alimaz/2017/10/24/enabling-aks-in-your-azure-subscription/

**Comment by msftkru** [comment]
also noticed we changed the cli command for aks create taking out --orchestration-type and modifying --dns-prefix to --dns-name-prefix

**Comment by amazaheri** [comment]
yeah it needs to be removed, can you do a PR?

**Comment by msftkru** [comment]
yeah, I working in my own fork so I don't fork up the repo again.  I'll submit a PR soon.

**Comment by rajeshagadi** [comment]
Team I have taken care of all of the above updates.
