### ISSUE TITLE
AKS module: 

### ISSUE THREAD

**Issue by rajeshagadi** [Microsoft/MTC_ContainerCamp#44]
Cluster creation fails with below issue:

 az aks create -g AKSWorkshopRG -n akscluster --dns-name-prefix=akstest --generate-ssh-keys
Finished service principal creation[##################################]  100Waiting for AAD role to propagate[###                                 ]  10.Waiting for AAD role to propagate[#######                             ]  20.AAD role propagation done[############################################]  100.0000%The credentials in ServicePrincipalProfile were invalid. Please see https://aka.ms/acs-sp-help for more details. (Details: adal: Refresh request failed. Status Code = '400')

**Comment by richross** [comment]
Yes, I've seen this as well.  If you encounter this during the camp, the suggestion is to rerun the command as it seems to work the second time.

**Comment by msftkru** [comment]
I've hit this twice as well.

**Comment by msftkru** [comment]
![image](https://user-images.githubusercontent.com/22481237/32286474-f73013aa-bf03-11e7-90ae-62150a94acdb.png)
