### ISSUE TITLE
MTC_ContainerCamp

### ISSUE THREAD

**Issue by JeromeIsaacVigne** [Microsoft/MTC_ContainerCamp#50]
In the description for creating your own Container image, the patch should be 
cd ~/MTC_ContainerCamp/modules/docker
cat Dockerfile

**Comment by amazaheri** [comment]
Thank you @JeromeIsaacVigne please feel free to submit a PR as you go through this, @larryms can you update?

**Comment by larryms** [comment]
created PR to fix this

**Comment by larryms** [comment]
closed per PR & issue #51
