### ISSUE TITLE
Move ReadingList application book images to EXP

### ISSUE THREAD

**Issue by RaviTella** [Microsoft/MTC_ContainerCamp#54]
Currently the book images are being served from a storage account that is not in EXP. Following tasks must be completed to move images to EXP.
1) Move images to EXP storage
2) Update Recommendation service with the new location of the images. 
3) Build and publish a new  image for the recommendation service

**Comment by amazaheri** [comment]
Are you still good to do this?

**Comment by RaviTella** [comment]
Images moved EXP. I retained the same names for storage account, blob and images. No code changes required.
